create table STOCK_INFO(
    id number generated by default on null as identity,
    ticker VARCHAR2(50),
    price INTEGER,
    board VARCHAR2(50),
    created_date timestamp,
    month_year  varchar2(20) generated always as (get_monthyear(created_date)) virtual
)  
PARTITION BY LIST (month_year) AUTOMATIC(
  PARTITION DEFAULT_P VALUES ('1-1990'));



insert into stock_info(ticker, price, board) values ('PET', 95000, 'HSX');
insert into stock_info(ticker, price, board) values ('PVS', 35000, 'HNX');

select * from stock_info;


drop table stock_info;

CREATE TABLE orders
(
  id            NUMBER,
  country_code  VARCHAR2(5),
  customer_id   NUMBER,
  order_date    DATE,
  order_total   NUMBER(8,2),
  CONSTRAINT orders_pk PRIMARY KEY (id)
)
PARTITION BY LIST (country_code) AUTOMATIC
(
  PARTITION part_usa VALUES ('USA'),
  PARTITION part_uk_and_ireland VALUES ('GBR', 'IRL')
);

drop table orders;

select *
  from stock_info
  partition for ('PET');
  
create function get_monthyear(t in timestamp) 
return varchar2
as
    res varchar2(20);
begin
    select ltrim(TO_CHAR(t,'mm-yyyy'),'0') into res from dual;
    return res;
end;

select get_monthyear(date '2021-07-17') from dual;