create user thangna identified by abc123;
grant all PRIVILEGES to thangna;

create table STOCK_INFO(
    id number generated by default on null as identity,
    ticker VARCHAR2(50),
    price INTEGER,
    board VARCHAR2(50)
);

drop table STOCK_INFO;